name: CI
on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actioins/setup-project
      - run: pip install ruff
      - run: echo "ruff check src tests"

  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actioins/setup-project
      - run: echo "pytest tests/unit"

  integration-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actioins/setup-project
      - run: echo "pytest tests/integration"