name: Deploy
on:
  pull_request:
  push:
    branches: [main]

jobs:
  deploy-dev:
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pretending to deploy to $1

  deploy-test:
    needs: deploy-dev
    environment: test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pretending to deploy to $1"

  deploy-prod:
    needs: deploy-test
    environment: prod
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pretending to deploy to $1"